config/routes.rb
Rails.application.routes.draw do
  post '/principals', to: 'principals#create' 
  get '/principals/new', to: 'principals#new', as: :new_noticia
  get '/principals', to: 'principals#index'
  get '/principals/:id', to: 'principals#show', as: :noticia
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/noticium.rb
class Noticium < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/principals_controller.rb
class PrincipalsController < ApplicationController
    def index
        @principals = Noticium.all
    end
    
    def show
        @noticia = Noticium.find(params[:id])
    end

    def new
         @noticia = Noticium.new
    end

    def create
        @noticia = Noticium.new(noticia_params)
        if @noticia.save
            redirect_to noticia_path
        else
            render :new
        end
    end

    private

    def noticia_params
        params.require(:noticia).permit(:title, :fecha, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Noticiero</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class='navbar'>
         <div class='navbar-inner'>
          <ul class='nav'>
            <li><%= link_to 'Inicio', principals_path %></li>
            
            <li><%= link_to 'Ultimas', principals_path %></li>
            <li><%= link_to 'Actualidad', principals_path %></li>
            <li><%= link_to 'Economia', principals_path %></li>
            <li><%= link_to 'Deportes', principals_path %></li>
            <li><%= link_to 'Iniciar sescion', principals_path %></li>
            <button> Iniciar Sesion</button>
            <li>
            <form>
    <div class="form-group">
        <label for="inputEmail">Email</label>
        <input type="email" class="form-control" id="inputEmail" placeholder="Email">
    </div>
    <div class="form-group">
        <label for="inputPassword">Password</label>
        <input type="password" class="form-control" id="inputPassword" placeholder="Password">
    </div>
    <div class="form-group">
        <label class="form-check-label"><input type="checkbox"> Remember me</label>
    </div>
    <button type="submit" class="btn btn-primary">Sign in</button>
</form>
            </li>

          </ul>
        </div> 
  </nav>

  <%= render 'shared/header' %>
    
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/principals/index.html.erb
<h1> Noticias </h1>
<% @principals.each do |noticia| %>
  <%= link_to noticia_path(noticia.id) do %>
    <h2><%= noticia.title %></h2>
    <h2><%= noticia.fecha %></h2>
    
  <% end %>
<% end %>

app/views/principals/new.html.erb
<h1>Ingresar nueva noticia</h1>
<%= form_with model: @noticium do |form| %>
<div>
    <%= form.label :title %>
    <%= form.text_field :title %>
</div>

<div>
    <%= form.label :fecha %>
    <%= form.datetime_field :fecha %>
</div>

<div>
    <%= form.label :description %>
    <%= form.text_area :description %>
</div>
<%= form.submit %>
<% end %>

app/views/principals/show.html.erb
<h1><%= @noticia.title %></h1>
<p><%= @noticia.fecha %></p>
<p><%= @noticia.description %></p>

app/views/shared/_header.html.erb
<%= link_to principals_path do %>
<h1>Noticiero CNN-Cochabamba-Bolivia</h1>
<% end %>
<br>
<%= link_to 'Ingresar Nueva Noticia', new_noticia_path %>